version: 2
updates:
- package-ecosystem: dotnet-sdk
  directory: "/"
  schedule:
    interval: weekly
  commit-message:
    prefix: "chore(deps)"
- package-ecosystem: nuget
  directory: "/Sentry.CrashReporter"
  schedule:
    interval: weekly
  commit-message:
    prefix: "chore(deps)"
- package-ecosystem: nuget
  directory: "/tests"
  schedule:
    interval: weekly
  groups:
    test-dependencies:
      patterns:
        - "*"
      group-by: dependency-name
  ignore:
    # https://fluentassertions.com/releases/#800
    - dependency-name: "FluentAssertions"
      versions: ["8.*"]
  commit-message:
    prefix: "test(deps)"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  commit-message:
    prefix: "ci(deps)"
