changelog:
  policy: auto
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Breaking Changes
      labels:
        - breaking
      commit_patterns:
        - "^(?<type>\\w+(?:\\((?<scope>[^)]+)\\))?!:\\s*)"
    - title: Features
      labels:
        - feature
      commit_patterns:
        - "^feat(?:\\([^\\)]+\\))?:\\s+"
    - title: Fixes
      labels:
        - fix
      commit_patterns:
        - "^fix(?:\\([^\\)]+\\))?:\\s+"
    - title: Dependencies
      labels:
        - dependencies
      commit_patterns:
        - "^(?:chore|build)\\(deps(?:-dev)?\\):\\s+"
    - title: Improvements
      labels:
        - improvement
      commit_patterns:
        - "^perf(?:\\([^\\)]+\\))?:\\s+"
        - "^build(?:\\([^\\)]+\\))?:\\s+"
