name: CI

on:
  push:
    branches:
      - main
      - release/**
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - release/**
  workflow_dispatch:

permissions:
  contents: read

env:
  STEP_TIMEOUT_MINUTES: 60

jobs:
  smoke_test:
    name: Smoke Test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Install Dependencies
        timeout-minutes: ${{ fromJSON(env.STEP_TIMEOUT_MINUTES) }}
        uses: "./.github/steps/install_dependencies"
        with:
          target-platform: "desktop"

      # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0

      - name: Build Sentry.CrashReporter (Debug)
        shell: pwsh
        run: msbuild ./Sentry.CrashReporter/Sentry.CrashReporter.csproj /r

  build:
    strategy:
      fail-fast: false
      matrix:
       include:
         - os: macos-latest
           rid: osx-arm64
         - os: ubuntu-latest
           rid: linux-x64
         - os: ubuntu-24.04-arm
           rid: linux-arm64
         - os: windows-latest
           rid: win-x64
         - os: windows-11-arm
           rid: win-arm64

    name: Build (${{ matrix.rid }})

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Resolve Variables
        id: vars
        shell: bash
        run: |
          if [[ "${{ github.ref_name }}" == release/* ]]; then
            version=${GITHUB_REF_NAME#release/}
          else
            version=${GITHUB_SHA::7}
          fi
          echo "artifact=sentry-desktop-crash-reporter-${version}-${{ matrix.rid }}" >> "$GITHUB_OUTPUT"

      - name: Install Dependencies
        timeout-minutes: ${{ fromJSON(env.STEP_TIMEOUT_MINUTES) }}
        uses: "./.github/steps/install_dependencies"
        with:
          target-platform: "desktop"

      - name: Build Sentry.CrashReporter (Release)
        shell: pwsh
        run: dotnet publish -f net9.0-desktop -r ${{ matrix.rid }} ./Sentry.CrashReporter/Sentry.CrashReporter.csproj -o ./build -bl:./build.binlog

      - name: Archive Artifacts
        shell: bash
        run: |
          mkdir ./artifacts
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            (cd ./build && 7z a -tzip "../artifacts/${{ steps.vars.outputs.artifact }}.zip" .)
          else
            tar czf "./artifacts/${{ steps.vars.outputs.artifact }}.tar.gz" -C ./build .
          fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: ${{ steps.vars.outputs.artifact }}
          path: ./artifacts

      - name: Upload Binlog
        if: ${{ !startsWith(github.ref_name, 'release/') }}
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: binlog-${{ matrix.rid }}
          path: ./build.binlog

  unit_test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Install Dependencies
        timeout-minutes: ${{ fromJSON(env.STEP_TIMEOUT_MINUTES) }}
        uses: "./.github/steps/install_dependencies"
        with:
          target-platform: "desktop"

      - name: Build Sentry.CrashReporter.Tests (Release)
        shell: pwsh
        run: dotnet build ./Sentry.CrashReporter.Tests/Sentry.CrashReporter.Tests.csproj /p:Configuration=Release /p:OverrideTargetFramework=net9.0

      - name: Run Unit Tests
        shell: pwsh
        run: dotnet test ./Sentry.CrashReporter.Tests/Sentry.CrashReporter.Tests.csproj --no-build -c Release --logger GitHubActions --blame-crash --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.SingleHit=true

      - name: Upload code coverage
        uses: jpnurmi/codecov-action@fix/coverlet
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Test Results
        if: ${{ always() && !startsWith(github.ref_name, 'release/') }}
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: unit-test-results
          path: |
            Sentry.CrashReporter.Tests/TestResults/

  ui_test:
    name: UI Tests
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Install Dependencies
        timeout-minutes: ${{ fromJSON(env.STEP_TIMEOUT_MINUTES) }}
        uses: "./.github/steps/install_dependencies"
        with:
          target-platform: "webassembly"

      - name: Build Sentry.CrashReporter (WebAssembly, Release)
        run: dotnet build -c Release -f net9.0-browserwasm -p:IsUiAutomationMappingEnabled=True Sentry.CrashReporter/Sentry.CrashReporter.csproj

      - name: Build Sentry.CrashReporter.UITests (Release)
        run: dotnet build -c Release -f net9.0 Sentry.CrashReporter.UITests/Sentry.CrashReporter.UITests.csproj

      - name: Run UI Tests
        id: run-ui-tests
        continue-on-error: true
        shell: pwsh
        run: .github/scripts/run-ui-tests.ps1

      - name: Retry UI Tests
        if: steps.run-ui-tests.outcome == 'failure'
        shell: pwsh
        run: .github/scripts/run-ui-tests.ps1

      - name: Upload Test Results
        if: ${{ always() && !startsWith(github.ref_name, 'release/') }}
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: ui-test-results
          path: |
            Sentry.CrashReporter.UITests/TestResults/

  runtime_test:
    name: Runtime Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Install Dependencies
        timeout-minutes: ${{ fromJSON(env.STEP_TIMEOUT_MINUTES) }}
        uses: "./.github/steps/install_dependencies"
        with:
          target-platform: "desktop"

      - name: Install Coverlet Tool
        run: dotnet tool restore

      - name: Build Sentry.CrashReporter.RuntimeTests.Host (Release)
        run: dotnet build -c Release -f net9.0-desktop Sentry.CrashReporter.RuntimeTests.Host/Sentry.CrashReporter.RuntimeTests.Host.csproj

      - name: Run Runtime Tests
        env:
          UNO_RUNTIME_TESTS_RUN_TESTS: '{}'
          UNO_RUNTIME_TESTS_OUTPUT_PATH: Sentry.CrashReporter.RuntimeTests/TestResults/RuntimeTests.xml
        run: |
          xvfb-run -a dotnet tool run coverlet -- \
            Sentry.CrashReporter.RuntimeTests.Host/bin/Release/net9.0-desktop/Sentry.CrashReporter.RuntimeTests.Host.dll \
            --target dotnet \
            --targetargs Sentry.CrashReporter.RuntimeTests.Host/bin/Release/net9.0-desktop/Sentry.CrashReporter.RuntimeTests.Host.dll \
            --output Sentry.CrashReporter.RuntimeTests/TestResults/ \
            --format cobertura \
            --single-hit \
            -v

      - name: Process Test Results
        if: always()
        shell: pwsh
        run: |
          $filePath = 'Sentry.CrashReporter.RuntimeTests/TestResults/RuntimeTests.xml'
          $content = Get-Content -Path $filePath -Raw
          $content -replace 'encoding="utf-16"', 'encoding="utf-8"' | Set-Content -Path $filePath -Encoding utf8 -NoNewline

      - name: Upload Test Results
        if: ${{ always() && !startsWith(github.ref_name, 'release/') }}
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: runtime-test-results
          path: |
            Sentry.CrashReporter.RuntimeTests/TestResults

      - name: Report Test Results
        uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2 # v3.0.0
        if: ${{ !cancelled() && !startsWith(github.ref_name, 'release/') }}
        with:
          name: Runtime Tests
          path: Sentry.CrashReporter.RuntimeTests/TestResults/RuntimeTests.xml
          reporter: dotnet-nunit

      - name: Upload Code Coverage
        uses: jpnurmi/codecov-action@fix/coverlet
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
